import { useEffect, useMemo, useState } from 'react';
import { buildHistoricalSeries, buildMarketStocks, computeIndicatorSummary, fetchMarketIndexes, fetchStockCandles, fetchStockQuotes, searchStocks, type AlertRule, type PeriodKey, type StockItem } from './data/stocks';

type Tab = 'market' | 'favorites' | 'search' | 'trade' | 'settings';
type Trade = { cash:number; holdings:{code:string;name:string;qty:number;avgPrice:number}[]; history:{side:'买入'|'卖出';name:string;qty:number;price:number;time:string}[] };
const seed=buildMarketStocks();
const initialTrade:Trade={cash:5000000,holdings:[],history:[]};
const periods:{key:PeriodKey;label:string}[]=[
 {key:'1m',label:'分时'},{key:'5m',label:'5分'},{key:'15m',label:'15分'},{key:'30m',label:'30分'},{key:'60m',label:'60分'},{key:'120m',label:'120分'},{key:'day',label:'日K'},{key:'week',label:'周K'},{key:'month',label:'月K'},{key:'year',label:'年K'}
];

function App(){
 const [tab,setTab]=useState<Tab>('market');
 const [stocks,setStocks]=useState<StockItem[]>(seed);
 const [indexes,setIndexes]=useState<StockItem[]>([]);
 const [code,setCode]=useState('sh600519');
 const [query,setQuery]=useState('');
 const [favorites,setFavorites]=useState<string[]>(()=>JSON.parse(localStorage.getItem('stock-app:favorites')||'[]'));
 const [alerts,setAlerts]=useState<Record<string,AlertRule>>(()=>JSON.parse(localStorage.getItem('stock-app:alerts')||'{}'));
 const [trade,setTrade]=useState<Trade>(()=>JSON.parse(localStorage.getItem('stock-app:trade')||JSON.stringify(initialTrade)));
 const [period,setPeriod]=useState<PeriodKey>('day');
 const [series,setSeries]=useState<{close:number;time:string}[]>([]);
 const [indicator,setIndicator]=useState<'macd'|'kdj'|'rsi'>('macd');
 const [loading,setLoading]=useState(true);
 const [source,setSource]=useState<'实时'|'降级'>('降级');
 const [voice,setVoice]=useState(true);
 const stock=useMemo(()=>stocks.find(item=>item.code===code)||stocks[0]||seed[0],[stocks,code]);
 const results=useMemo(()=>searchStocks(query,stocks),[query,stocks]);
 const watchlist=useMemo(()=>stocks.filter(item=>favorites.includes(item.code)),[stocks,favorites]);
 const summary=useMemo(()=>computeIndicatorSummary(series.length?series:buildHistoricalSeries(stock,period)),[series,stock,period]);
 useEffect(()=>{localStorage.setItem('stock-app:favorites',JSON.stringify(favorites));},[favorites]);
 useEffect(()=>{localStorage.setItem('stock-app:alerts',JSON.stringify(alerts));},[alerts]);
 useEffect(()=>{localStorage.setItem('stock-app:trade',JSON.stringify(trade));},[trade]);
 useEffect(()=>{let cancelled=false;const refresh=async()=>{const [quotes,market]=await Promise.all([fetchStockQuotes(),fetchMarketIndexes()]);if(cancelled)return;setStocks(quotes);setIndexes(market);setSource(quotes.some(item=>item.volume>0)?'实时':'降级');setLoading(false);};refresh().catch(()=>{if(!cancelled){setStocks(seed);setSource('降级');setLoading(false);}});const timer=window.setInterval(refresh,30000);return()=>{cancelled=true;window.clearInterval(timer);};},[]);
 useEffect(()=>{let cancelled=false;setSeries([]);fetchStockCandles(stock.code,period).then(data=>{if(!cancelled)setSeries(data);}).catch(()=>{if(!cancelled)setSeries(buildHistoricalSeries(stock,period));});return()=>{cancelled=true;};},[stock.code,period]);
 useEffect(()=>{watchlist.forEach(item=>{const rule=alerts[item.code];const hit=rule&&((rule.priceAbove!==undefined&&item.price>=rule.priceAbove)||(rule.priceBelow!==undefined&&item.price<=rule.priceBelow)||(rule.changeAbove!==undefined&&item.percent>=rule.changeAbove)||(rule.changeBelow!==undefined&&item.percent<=rule.changeBelow));if(hit&&!rule.lastTriggered){const message=`${item.name}${item.percent>=0?'上涨':'下跌'}${Math.abs(item.percent).toFixed(2)}%，现价${item.price.toFixed(2)}`;if('Notification'in window&&Notification.permission==='granted')new Notification('A股预警',{body:message});if(voice&&'speechSynthesis'in window)window.speechSynthesis.speak(new SpeechSynthesisUtterance(message));setAlerts(old=>({...old,[item.code]:{...old[item.code],lastTriggered:true}}));}});},[watchlist,alerts,voice]);
 const toggleFavorite=(itemCode:string)=>setFavorites(old=>old.includes(itemCode)?old.filter(x=>x!==itemCode):[...old,itemCode]);
 const openStock=(itemCode:string)=>{setCode(itemCode);setTab('market');};
 const buy=()=>{const qty=100;const total=stock.price*qty+Math.max(5,stock.price*qty*.00025);if(trade.cash<total)return alert('可用资金不足');setTrade(old=>{const found=old.holdings.find(x=>x.code===stock.code);const holdings=found?old.holdings.map(x=>x.code===stock.code?{...x,qty:x.qty+qty,avgPrice:(x.avgPrice*x.qty+stock.price*qty)/(x.qty+qty)}:x):[...old.holdings,{code:stock.code,name:stock.name,qty,avgPrice:stock.price}];return {...old,cash:old.cash-total,holdings,history:[{side:'买入',name:stock.name,qty,price:stock.price,time:new Date().toLocaleTimeString()},...old.history]};});};
 const sell=()=>{const found=trade.holdings.find(x=>x.code===stock.code);if(!found)return alert('当前没有该股票持仓');const qty=Math.min(100,found.qty);const amount=stock.price*qty-Math.max(5,stock.price*qty*.00125);setTrade(old=>({...old,cash:old.cash+amount,holdings:old.holdings.map(x=>x.code===stock.code?{...x,qty:x.qty-qty}:x).filter(x=>x.qty>0),history:[{side:'卖出',name:stock.name,qty,price:stock.price,time:new Date().toLocaleTimeString()},...old.history]}));};
 const askNotification=async()=>{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();};
 const totalValue=trade.holdings.reduce((sum,item)=>sum+(stocks.find(x=>x.code===item.code)?.price||item.avgPrice)*item.qty,0);
 const values=series.map(x=>x.close);const min=Math.min(...values,stock.price*.94);const max=Math.max(...values,stock.price*1.06);const path=values.map((value,i)=>`${i?'L':'M'} ${(i/Math.max(values.length-1,1))*340} ${220-((value-min)/Math.max(max-min,1))*220}`).join(' ');
 const list=(items:StockItem[])=> <div className="search-results">{items.map(item=><div className="search-item" key={item.code} onClick={()=>openStock(item.code)}><div><strong>{item.name}</strong><small>{item.code}</small></div><div><span>{item.price.toFixed(2)}</span><span className={item.percent>=0?'up':'down'}>{item.percent>=0?'+':''}{item.percent.toFixed(2)}%</span></div><button className="mini-button" onClick={e=>{e.stopPropagation();toggleFavorite(item.code);}}>{favorites.includes(item.code)?'已加':'自选'}</button></div>)}</div>;
 return <div className="app-shell"><header className="topbar"><div><p className="eyebrow">A股专业股票分析平台 · {source}数据</p><h1>智能行情助手</h1></div><span className="status-pill">{loading?'同步中':source}</span></header><nav className="tabbar">{(['market','favorites','search','trade','settings'] as Tab[]).map(item=><button key={item} className={tab===item?'tab active':'tab'} onClick={()=>setTab(item)}>{{market:'行情',favorites:'自选',search:'搜索',trade:'交易',settings:'设置'}[item]}</button>)}</nav>
 {tab==='market'&&<main className="page"><section className="index-grid">{(indexes.length?indexes:seed.slice(9)).map(item=><div className="card index-card" key={item.code}><span>{item.name}</span><strong>{item.price.toFixed(2)}</strong><small className={item.change>=0?'up':'down'}>{item.change>=0?'+':''}{item.change.toFixed(2)} ({item.percent.toFixed(2)}%)</small></div>)}</section><section className="card section-card"><div className="section-header"><h2>市场排行</h2></div>{list([...stocks].sort((a,b)=>Math.abs(b.percent)-Math.abs(a.percent)).slice(0,8))}</section><section className="card section-card"><div className="detail-header"><div><small>{stock.code}</small><h2>{stock.name}</h2></div><button className="mini-button" onClick={()=>toggleFavorite(stock.code)}>{favorites.includes(stock.code)?'已关注':'关注'}</button></div><div className="price-strip"><strong>{stock.price.toFixed(2)}</strong><span className={stock.change>=0?'up':'down'}>{stock.change>=0?'+':''}{stock.change.toFixed(2)} ({stock.percent>=0?'+':''}{stock.percent.toFixed(2)}%)</span></div><div className="period-tabs">{periods.map(item=><button className={period===item.key?'tab-chip active':'tab-chip'} key={item.key} onClick={()=>setPeriod(item.key)}>{item.label}</button>)}</div><svg viewBox="0 0 340 220" className="chart-svg"><path d={path} fill="none" stroke="#f97316" strokeWidth="2.5" /></svg><div className="signal-row">{summary.buySignals.map(x=><span className="signal-pill buy" key={x}>{x}</span>)}{summary.sellSignals.map(x=><span className="signal-pill sell" key={x}>{x}</span>)}</div><div className="indicator-tabs">{(['macd','kdj','rsi'] as const).map(x=><button className={indicator===x?'tab-chip active':'tab-chip'} key={x} onClick={()=>setIndicator(x)}>{x.toUpperCase()}</button>)}</div><div className="indicator-panel"><div className="metric-box"><span>{indicator.toUpperCase()}</span><strong>{summary[indicator].toFixed(2)}</strong></div><div className="metric-box"><span>形态判断</span><strong>{summary.pattern}</strong></div></div></section></main>}
 {tab==='favorites'&&<main className="page"><section className="card section-card"><div className="section-header"><h2>自选股</h2><button className="ghost-button" onClick={()=>setTab('search')}>添加</button></div>{watchlist.length?list(watchlist):<p className="empty-card">暂无自选股</p>}</section></main>}
 {tab==='search'&&<main className="page"><section className="card section-card"><h2>股票搜索</h2><input className="search-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="代码 / 名称 / 拼音" />{list(results)}</section></main>}
 {tab==='trade'&&<main className="page"><section className="summary-grid"><div className="card summary-card"><span>可用资金</span><strong>{trade.cash.toFixed(2)}</strong></div><div className="card summary-card"><span>持仓市值</span><strong>{totalValue.toFixed(2)}</strong></div><div className="card summary-card"><span>总资产</span><strong>{(trade.cash+totalValue).toFixed(2)}</strong></div></section><section className="card section-card"><h2>模拟交易 · {stock.name}</h2><div className="trade-panel"><span>{stock.price.toFixed(2)}</span><button className="buy-button" onClick={buy}>买入100股</button><button className="sell-button" onClick={sell}>卖出100股</button></div>{trade.history.map((item,index)=><div className="history-row" key={`${item.time}-${index}`}><span>{item.side}</span><span>{item.name}</span><span>{item.qty}股</span><span>{item.price.toFixed(2)}</span></div>)}</section></main>}
 {tab==='settings'&&<main className="page"><section className="card section-card"><h2>设置与预警</h2><label className="toggle-row"><span>语音播报</span><input type="checkbox" checked={voice} onChange={()=>setVoice(!voice)} /></label><button className="ghost-button" onClick={askNotification}>请求通知权限</button>{watchlist.map(item=>{const rule=alerts[item.code]||{};return <div className="card-inner alert-setting" key={item.code}><strong>{item.name}</strong><div className="alert-inputs"><input type="number" placeholder="价格高于" defaultValue={rule.priceAbove||''} onBlur={e=>setAlerts(a=>({...a,[item.code]:{...a[item.code],priceAbove:Number(e.target.value)||undefined}}))}/><input type="number" placeholder="价格低于" defaultValue={rule.priceBelow||''} onBlur={e=>setAlerts(a=>({...a,[item.code]:{...a[item.code],priceBelow:Number(e.target.value)||undefined}}))}/></div></div>;})}</section></main>}
 </div>;
}
export default App;
